# Use Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy Python program
COPY jardinvinod_module7_04.py .

# Run the Python program
CMD ["python", "jardinvinod_module7_04.py"]