# Use a small official Python image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python program into the container
COPY jardinvinod_module7_01.py .

# Run the Python program
CMD ["python", "jardinvinod_module7_01.py"]