# Use a small Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy Python program
COPY jardinvinod_module7_02.py .

# Run Python program
CMD ["python", "jardinvinod_module7_02.py"]